# Builds a Hugo web site

variables:
  hugo_ver: '0.53'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    curl -sL https://github.com/gohugoio/hugo/releases/download/v$(hugo_ver)/hugo_extended_$(hugo_ver)_Linux-64bit.tar.gz -o $(Build.BinariesDirectory)/hugo_$(hugo_ver).tar.gz
    cd $(Build.BinariesDirectory)
    tar xzf hugo_$(hugo_ver).tar.gz
  displayName: 'Download Hugo'

- script:
    $(Build.BinariesDirectory)/hugo -v -d $(Build.ArtifactStagingDirectory)
  displayName: 'Generate site'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'site'
    publishLocation: 'Container'
