baseurl = "https://tfsaggregator.github.io/"
languageCode = "en-us"
title = "Aggregator"
theme = "hugo-book"
metadataformat = "yaml"
canonifyurls = "true"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
enableGitInfo = "true"

[params]
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = true
  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = "https://github.com/tfsaggregator/tfsaggregator-docs-hugo"
  # Enable 'Edit this page' links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to the site directory.
  BookEditPath = 'edit/master/content'

  # Author of the site, will be used in meta information
  author = "TFS Aggregator Team"
  # Description of the site, will be used in meta information
  description = "Aggregator Documentation"
